// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsg37FIdbDuJkpxwRmioQyVaGQARAnFqw',
    appId: '1:273545885824:web:455318043dc87d3b970e65',
    messagingSenderId: '273545885824',
    projectId: 'appbox-test',
    authDomain: 'appbox-test.firebaseapp.com',
    storageBucket: 'appbox-test.appspot.com',
    measurementId: 'G-ZP203JBMQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4PF_Su4Vyi-ZThU5wOYe3ldWAb-rAd-4',
    appId: '1:273545885824:android:9cd96ef5efc3343b970e65',
    messagingSenderId: '273545885824',
    projectId: 'appbox-test',
    storageBucket: 'appbox-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmZRrQSBokx64wBS_vW084np5uxd0PKc',
    appId: '1:273545885824:ios:ad32c6b72cdbb086970e65',
    messagingSenderId: '273545885824',
    projectId: 'appbox-test',
    storageBucket: 'appbox-test.appspot.com',
    iosBundleId: 'app3test.boxapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTmZRrQSBokx64wBS_vW084np5uxd0PKc',
    appId: '1:273545885824:ios:6b148c99d001528b970e65',
    messagingSenderId: '273545885824',
    projectId: 'appbox-test',
    storageBucket: 'appbox-test.appspot.com',
    iosBundleId: 'app3test.boxapp.RunnerTests',
  );
}
